-- Durable checks only. Inactivity never disables or deletes a method.
CREATE TABLE IF NOT EXISTS ai_ops_skill_maintenance (
  check_id VARCHAR(64) NOT NULL PRIMARY KEY,
  project_id VARCHAR(128) NOT NULL,
  skill_id VARCHAR(128) NOT NULL,
  base_version INT NOT NULL,
  base_skill_hash VARCHAR(128) NOT NULL,
  base_package_hash VARCHAR(128) NOT NULL,
  base_content MEDIUMTEXT NOT NULL,
  kind VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  reason VARCHAR(128) NOT NULL,
  body_tokens INT NOT NULL,
  tokenizer VARCHAR(48) NOT NULL,
  patch_count INT NOT NULL,
  automatic TINYINT NOT NULL,
  last_use_at TIMESTAMP(3) NULL,
  attempts INT NOT NULL DEFAULT 0,
  lease_token VARCHAR(80) NULL,
  lease_until TIMESTAMP(3) NULL,
  next_run_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  evidence_json MEDIUMTEXT NULL,
  published_version INT NOT NULL DEFAULT 0,
  reviewed_by VARCHAR(128) NOT NULL DEFAULT '',
  review_reason VARCHAR(1024) NOT NULL DEFAULT '',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_skill_maintenance_due(status,next_run_at),
  KEY idx_skill_maintenance_subject(project_id,skill_id,kind,base_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
