CREATE TABLE IF NOT EXISTS `ai_ops_agent_audit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `analysis_id` VARCHAR(64) NOT NULL COMMENT '分析ID',
  `success` TINYINT NOT NULL COMMENT '是否成功',
  `question` TEXT NULL COMMENT '用户问题',
  `intent` VARCHAR(64) NULL COMMENT '主Agent意图',
  `range_minutes` INT NULL COMMENT '日志时间窗口',
  `prom_window` VARCHAR(16) NULL COMMENT 'Prometheus rate窗口',
  `generated_at` VARCHAR(32) NULL COMMENT '分析生成时间',
  `duration_ms` BIGINT NULL COMMENT '耗时毫秒',
  `selected_sources_json` TEXT NULL COMMENT '计划选择数据源',
  `executed_sources_json` TEXT NULL COMMENT '实际执行数据源',
  `skipped_sources_json` TEXT NULL COMMENT '跳过数据源',
  `result_statuses_json` TEXT NULL COMMENT '子Agent结果状态',
  `insight_levels_json` TEXT NULL COMMENT '规则洞察等级',
  `conclusion` TEXT NULL COMMENT '首要结论',
  `error_message` TEXT NULL COMMENT '失败原因',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_analysis_id` (`analysis_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_success` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='示例运维AI分析审计表';
