CREATE TABLE IF NOT EXISTS `ai_ops_task_context` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_id` VARCHAR(80) NOT NULL,
  `session_id` VARCHAR(80) NOT NULL DEFAULT '',
  `project_id` VARCHAR(128) NOT NULL DEFAULT '',
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '',
  `task_state` VARCHAR(32) NOT NULL DEFAULT '',
  `context_json` MEDIUMTEXT NOT NULL,
  `summary` TEXT NULL,
  `last_event_id` BIGINT DEFAULT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_run_id` (`run_id`),
  KEY `idx_session_id` (`session_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运维Agent当前任务上下文';

CREATE TABLE IF NOT EXISTS `ai_ops_context_memory` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `memory_id` VARCHAR(80) NOT NULL,
  `scope_type` VARCHAR(24) NOT NULL COMMENT 'USER/PROJECT',
  `scope_id` VARCHAR(128) NOT NULL COMMENT 'userId/projectId',
  `memory_type` VARCHAR(64) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `summary` VARCHAR(1000) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `keywords` VARCHAR(1000) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `confidence` DECIMAL(5,4) NOT NULL DEFAULT 0.8000,
  `source_type` VARCHAR(32) NOT NULL DEFAULT '',
  `source_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_message_hash` VARCHAR(64) NOT NULL DEFAULT '',
  `created_by` VARCHAR(128) NOT NULL DEFAULT '',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expire_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_memory_id` (`memory_id`),
  KEY `idx_scope_type_id` (`scope_type`, `scope_id`),
  KEY `idx_scope_type_memory` (`scope_type`, `scope_id`, `memory_type`),
  KEY `idx_status_update` (`status`, `update_time`),
  CONSTRAINT `ck_context_memory_scope` CHECK (`scope_type` IN ('USER', 'PROJECT')),
  CONSTRAINT `ck_context_memory_type` CHECK (`memory_type` IN (
    'USER_PREFERENCE',
    'USER_WORKFLOW',
    'USER_DOMAIN_FOCUS',
    'PROJECT_CONTEXT',
    'PROJECT_CONVENTION',
    'PROJECT_GLOSSARY'
  ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户和项目长期上下文记忆';

CREATE TABLE IF NOT EXISTS `ai_ops_runtime_context_bundle` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bundle_id` VARCHAR(80) NOT NULL,
  `bundle_hash` VARCHAR(128) NOT NULL,
  `session_id` VARCHAR(80) NOT NULL DEFAULT '',
  `run_id` VARCHAR(80) NOT NULL DEFAULT '',
  `project_id` VARCHAR(128) NOT NULL DEFAULT '',
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '',
  `actor` VARCHAR(128) NOT NULL DEFAULT '',
  `memory_context_hash` VARCHAR(128) NOT NULL DEFAULT '',
  `memory_refs_json` MEDIUMTEXT NULL,
  `used_skill_version_refs_json` MEDIUMTEXT NULL,
  `used_skill_refs_hash` VARCHAR(128) NOT NULL DEFAULT '',
  `toolset_boundary_hash` VARCHAR(128) NOT NULL DEFAULT '',
  `runtime_boundary_hash` VARCHAR(128) NOT NULL DEFAULT '',
  `bundle_json` MEDIUMTEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bundle_id` (`bundle_id`),
  KEY `idx_session_time` (`session_id`, `create_time`),
  KEY `idx_project_time` (`project_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运维运行时上下文Bundle表';
