CREATE TABLE IF NOT EXISTS `ai_ops_skill_run_episode` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `episode_id` VARCHAR(80) NOT NULL,
  `project_id` VARCHAR(128) NOT NULL,
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '',
  `run_id` VARCHAR(100) NOT NULL,
  `session_id` VARCHAR(100) NOT NULL DEFAULT '',
  `task_template_json` MEDIUMTEXT NOT NULL,
  `task_template_hash` VARCHAR(64) NOT NULL,
  `abstract_trajectory_json` MEDIUMTEXT NOT NULL,
  `trajectory_hash` VARCHAR(64) NOT NULL,
  `outcome` VARCHAR(32) NOT NULL,
  `evidence_refs_json` MEDIUMTEXT NOT NULL,
  `final_summary` TEXT NULL,
  `event_count` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'COMPLETED',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_episode_id` (`episode_id`),
  UNIQUE KEY `uk_skill_episode_run` (`project_id`, `run_id`),
  KEY `idx_skill_episode_template` (`project_id`, `task_template_hash`, `trajectory_hash`),
  KEY `idx_skill_episode_created` (`project_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Skill沉淀前的结构化Run Episode';

CREATE TABLE IF NOT EXISTS `ai_ops_skill_observation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `observation_id` VARCHAR(80) NOT NULL,
  `episode_id` VARCHAR(80) NOT NULL,
  `project_id` VARCHAR(128) NOT NULL,
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '',
  `run_id` VARCHAR(100) NOT NULL,
  `observation_type` VARCHAR(64) NOT NULL,
  `cluster_key` VARCHAR(64) NOT NULL,
  `task_template_hash` VARCHAR(64) NOT NULL,
  `trajectory_hash` VARCHAR(64) NOT NULL,
  `content_json` MEDIUMTEXT NOT NULL,
  `evidence_refs_json` MEDIUMTEXT NOT NULL,
  `outcome` VARCHAR(32) NOT NULL,
  `quality_score` DECIMAL(8,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'OBSERVED',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_observation_id` (`observation_id`),
  UNIQUE KEY `uk_skill_observation_run_type` (`project_id`, `run_id`, `observation_type`),
  KEY `idx_skill_observation_cluster` (`project_id`, `agent_id`, `cluster_key`, `status`),
  KEY `idx_skill_observation_episode` (`episode_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单次Run提取的非执行型Skill观察';

CREATE TABLE IF NOT EXISTS `ai_ops_skill_experience_cluster` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` VARCHAR(128) NOT NULL,
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '',
  `cluster_key` VARCHAR(64) NOT NULL,
  `observation_count` INT NOT NULL DEFAULT 0,
  `successful_count` INT NOT NULL DEFAULT 0,
  `evidence_count` INT NOT NULL DEFAULT 0,
  `latest_observation_id` VARCHAR(80) NOT NULL,
  `candidate_id` VARCHAR(80) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACCUMULATING',
  `version` INT NOT NULL DEFAULT 1,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_experience_cluster` (`project_id`, `agent_id`, `cluster_key`),
  KEY `idx_skill_experience_status` (`project_id`, `status`, `observation_count`),
  KEY `idx_skill_experience_candidate` (`candidate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='同类Observation原子聚合与晋升状态';
