CREATE TABLE IF NOT EXISTS ai_ops_change_verification_job (
    event_key CHAR(64) PRIMARY KEY,
    project_id VARCHAR(128) NOT NULL,
    package_id VARCHAR(80) NOT NULL,
    approved_version INT NOT NULL,
    approved_hash VARCHAR(128) NOT NULL,
    landing_run_id VARCHAR(80) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    workflow_id VARCHAR(80) NOT NULL,
    workflow_version INT NOT NULL,
    workflow_hash VARCHAR(128) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    session_id VARCHAR(80) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    next_attempt_at TIMESTAMP(3) NOT NULL,
    lease_token VARCHAR(64) NOT NULL DEFAULT '',
    lease_until TIMESTAMP(3) NULL,
    failures INT NOT NULL DEFAULT 0,
    last_error VARCHAR(300) NOT NULL DEFAULT '',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_change_verification_run (run_id),
    KEY idx_change_verification_due (status, next_attempt_at),
    KEY idx_change_verification_project (project_id, package_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
