package cn.lgs.orbisops.domain.agentdefinition.compilation;

public enum WorkflowCompilationErrorCode {
    SCHEMA_INVALID,
    NODE_TYPE_INVALID,
    NODE_CONFIG_INVALID,
    RULE_INVALID,
    EDGE_INVALID,
    TOPOLOGY_INVALID,
    CONTROL_FLOW_INVALID,
    CAPABILITY_REFERENCE_INVALID,
    SECURITY_BOUNDARY_INVALID,
    NODE_COMPILER_NOT_FOUND,
    NODE_COMPILER_DUPLICATE,
    COMPILED_PLAN_INVALID,
    INTERNAL_ERROR
}
