package cn.lgs.orbisops.trigger.ops;

import java.util.List;

/**
 * Query strategy generated by a datasource sub-agent before it acts.
 */
public record OpsSubAgentDecision(boolean llmGenerated,
                                  String reason,
                                  Integer rangeMinutes,
                                  String promWindow,
                                  Boolean includeRecentLogs,
                                  String retrievalMode,
                                  String queryFocus,
                                  Boolean requireExactFilters,
                                  List<String> expectedEvidence) {
}
