export interface OpsChangePackageCapabilities {
  canView?: boolean;
  canPrepare?: boolean;
  canRevise?: boolean;
  canSubmitReview?: boolean;
  canApprove?: boolean;
  canReject?: boolean;
  canLand?: boolean;
  canCleanup?: boolean;
}

export interface OpsChangePackage {
  packageId: string;
  sessionId?: string;
  incidentId?: string;
  projectId: string;
  preparationAgentId?: string;
  preparationAgentVersion?: number;
  packageType: string;
  status: string;
  productQueue?: 'PENDING' | 'RUNNING' | 'INTERVENTION' | 'HISTORY';
  version: number;
  approvedVersion?: number;
  packageHash?: string;
  approvedPackageHash?: string;
  objective?: string;
  summary?: string;
  evidenceJson?: string;
  toolBindingsJson?: string;
  preflightResultJson?: string;
  dryRunResultJson?: string;
  validationAssessment?: string;
  reasonCode?: string;
  approvalBoundaryJson?: string;
  preferredPlanJson?: string;
  adjustmentPolicyJson?: string;
  riskLevel?: string;
  targetEnvironment?: string;
  targetScopeJson?: string;
  allowedToolsJson?: string;
  forbiddenToolsJson?: string;
  branchName?: string;
  baseBranch?: string;
  targetBranch?: string;
  baseCommit?: string;
  repairWorkspaceId?: string;
  repositoryId?: string;
  serviceId?: string;
  repairCommit?: string;
  diffSummary?: string;
  diffHash?: string;
  testProofHash?: string;
  changedFilesJson?: string;
  codeEvidenceJson?: string;
  bashEvidenceJson?: string;
  lspEvidenceJson?: string;
  mcpStepsJson?: string;
  rollbackStepsJson?: string;
  verificationCriteriaJson?: string;
  ciResultJson?: string;
  landingPlanJson?: string;
  landingPlan?: Record<string, any> | Array<Record<string, any>>;
  mcpSteps?: Array<Record<string, any>>;
  approvedSnapshot?: Record<string, any>;
  contextBundleId?: string;
  contextBundleHash?: string;
  memoryContextRefs?: Array<Record<string, any>>;
  usedSkillVersionRefs?: Array<Record<string, any>>;
  usedSkillRefsHash?: string;
  toolsetRefs?: Array<Record<string, any>>;
  toolsetBoundaryHash?: string;
  policyRefs?: Array<Record<string, any>>;
  policyHash?: string;
  runtimeBoundaryHash?: string;
  approvalBoundaryHash?: string;
  trustedProofRefs?: Array<Record<string, any>>;
  validationReport?: Record<string, any>;
  allowedLandingAdjustmentsJson?: string;
  landingResultJson?: string;
  failureSummaryJson?: string;
  cleanupPlanJson?: string;
  createBy?: string;
  approveBy?: string;
  createTime?: string;
  updateTime?: string;
  approvedAt?: string;
  capabilities?: OpsChangePackageCapabilities;
  canView?: boolean;
  canPrepare?: boolean;
  canRevise?: boolean;
  canSubmitReview?: boolean;
  canApprove?: boolean;
  canReject?: boolean;
  canLand?: boolean;
  canCleanup?: boolean;
  [key: string]: any;
}

export interface OpsChangePackageEvent {
  eventId?: string;
  packageId: string;
  eventType: string;
  actor?: string;
  summary?: string;
  payloadJson?: string;
  createTime?: string;
  [key: string]: any;
}

export interface OpsLandingOperationRun {
  operationRunId: string;
  landingRunId?: string;
  packageId: string;
  projectId: string;
  approvedVersion?: number;
  approvedPackageHash?: string;
  operationId?: string;
  operationHash?: string;
  adapterType?: string;
  toolsetId?: string;
  toolName?: string;
  resourceKey?: string;
  effectType?: string;
  stage?: string;
  status?: string;
  factStatus?: string;
  reasonCode?: string;
  resultId?: string;
  outputHash?: string;
  preconditionResult?: Record<string, any>;
  executionResult?: Record<string, any>;
  postCheckResult?: Record<string, any>;
  result?: Record<string, any>;
  startedAt?: string;
  finishedAt?: string;
  rollbackStatus?: string;
  rollbackResult?: Record<string, any>;
  rollbackStartedAt?: string;
  rollbackFinishedAt?: string;
}
